In [160]:
import numpy as np
import csv

file = open('/home/johannes/Work/INF3490/oblig1/european_cities.csv', 'r+')
reader = csv.reader(file,delimiter=";")

distance = np.zeros((24,24))
cities = []

i = 0
for row in reader:
    #print row
    if i == 0:
        for j in range(len(row)):
            cities.append(row[j])
    else:
        for j in range(len(distance)):
            distance[i-1,j] = float(row[j])
    i += 1
        



In [162]:
# Exhaustive search

A = distance[0:4,0:4]

from itertools import permutations

tour = np.zeros(len(A)+1)
  
for i in range(len(A)):
    print i
    tour[0] = A[i,i]
    temp_A1 = np.delete(A,i,1)
    for j in permutations(temp_A1[i]):
        tour[1] = j[0]
        x1,y1 = np.where(temp_A1 == j[0])
        x2,y2 = np.where(temp_A1[:,y1] == 0) # x2
        temp_A2 = np.delete(temp_A1,y1,1)
        print temp_A2
        for k in permutations(temp_A2[int(x2)]):
            tour[2] = k[0]
            x1,y1 = np.where(temp_A2 == k[0])
            x2,y2 = np.where(temp_A2[:,y1] == 0)
            temp_A3 = np.delete(temp_A2,y1,1)
            tour[3] = temp_A3[x2]
            tour[4] = temp_A3[i]
            print k
            
        #tour[2] = temp_A2[x2]
        #tour[3] = temp_A2[i]
        #print tour
    
    
    


    
    
    
#def tour_len(t, d)
    
#def tsp_naive_solve(d):
#    btl, best_tour = min((tour_len(t, d), t) for t in permutations(range(1, len(d))))
#    return best_tour   
    
    

    
    
#travel_route = np.zeros(len(A)+1)
#best_cities = np.zeros(len(A))
#best = 1000000
#for i in range(len(A)):                             # go through each vector with different start city
#    for j in permutations(A[i]):                    # create the permutations
#        travel_route = np.append(j,j[0])
#        temp = np.sum(np.absolute(np.diff(travel_route)))      # find the total distance
#        if temp < best:                 # find the lowest distance
#            best = temp                 # save the lowest value
#            best_cities = travel_route            # save the best travel route
#            which_city = cities[i]
            
#def city_names(start):
    #vec = np.zeros
    #vec = A[start]
 #   return vec

#print best_cities, best
#print city_names(which_city)
#print best, best_cities
#print which_city
        

0
[[ 1497.61  1062.89]
 [  999.25  1372.59]
 [    0.     651.62]
 [  651.62     0.  ]]
(999.25, 1372.5899999999999)
(1372.5899999999999, 999.25)
[[ 1497.61  1062.89]
 [  999.25  1372.59]
 [    0.     651.62]
 [  651.62     0.  ]]
(999.25, 1372.5899999999999)
(1372.5899999999999, 999.25)
[[ 1528.13  1062.89]
 [    0.    1372.59]
 [  999.25   651.62]
 [ 1372.59     0.  ]]
(999.25, 651.62)
(651.62, 999.25)
[[ 1528.13  1062.89]
 [    0.    1372.59]
 [  999.25   651.62]
 [ 1372.59     0.  ]]
(999.25, 651.62)
(651.62, 999.25)
[[ 1528.13  1497.61]
 [    0.     999.25]
 [  999.25     0.  ]
 [ 1372.59   651.62]]
(1372.5899999999999, 651.62)
(651.62, 1372.5899999999999)
[[ 1528.13  1497.61]
 [    0.     999.25]
 [  999.25     0.  ]
 [ 1372.59   651.62]]
(1372.5899999999999, 651.62)
(651.62, 1372.5899999999999)
1
[[ 1497.61  1062.89]
 [  999.25  1372.59]
 [    0.     651.62]
 [  651.62     0.  ]]
(1497.6099999999999, 1062.8900000000001)
(1062.8900000000001, 1497.6099999999999)
[[ 1497.61  1062.89